import Foundation
import SwiftUI

/// A period-over-period change for a metric. `lowerIsBetter` governs how the delta
/// is styled (e.g. resting HR going down is "good"; HRV going down is "bad";
/// peak HR going up or down is neither).
struct TrendDelta: Hashable {
    let current: Double?
    let previous: Double?
    /// nil = neutral (no opinion), true = lower is better, false = higher is better.
    let lowerIsBetter: Bool?

    var absoluteChange: Double? {
        guard let c = current, let p = previous else { return nil }
        return c - p
    }

    var percentChange: Double? {
        guard let c = current, let p = previous, p != 0 else { return nil }
        return (c - p) / p
    }

    enum Direction { case up, down, neutral }

    var direction: Direction {
        guard let d = absoluteChange else { return .neutral }
        if abs(d) < 0.5 { return .neutral }
        return d > 0 ? .up : .down
    }

    /// Is this change an improvement? Uses `lowerIsBetter` to decide.
    /// Returns nil when we have no opinion.
    var isImprovement: Bool? {
        guard let lowerIsBetter, direction != .neutral else { return nil }
        switch direction {
        case .down: return lowerIsBetter
        case .up:   return !lowerIsBetter
        case .neutral: return nil
        }
    }

    var arrow: String {
        switch direction {
        case .up: return "arrow.up"
        case .down: return "arrow.down"
        case .neutral: return "minus"
        }
    }

    /// Color for the arrow/delta text.
    var tint: Color {
        guard direction != .neutral else { return .secondary }
        if let good = isImprovement {
            return good ? .green : .orange
        }
        return .secondary
    }

    /// Short formatted delta, e.g. "-2", "+3".
    var shortString: String? {
        guard let d = absoluteChange, abs(d) >= 0.5 else { return nil }
        let sign = d > 0 ? "+" : "−"
        return "\(sign)\(Int(abs(d).rounded()))"
    }
}

/// A tint used for Insight cards. Color is not Hashable on iOS 16, so we keep
/// this enum Hashable and map to Color at render time.
enum InsightTint: Hashable {
    case pink, green, blue, orange, red, gray, mint, purple
    case zone(HeartRateZone)

    var color: Color {
        switch self {
        case .pink:   return .pink
        case .green:  return .green
        case .blue:   return .blue
        case .orange: return .orange
        case .red:    return .red
        case .gray:   return .gray
        case .mint:   return .mint
        case .purple: return .purple
        case .zone(let z): return z.color
        }
    }
}

/// A small human-readable insight card, generated by the view model.
struct Insight: Identifiable, Hashable {
    let id: UUID
    let icon: String
    let title: String
    let detail: String
    let tint: InsightTint

    init(id: UUID = UUID(), icon: String, title: String, detail: String, tint: InsightTint) {
        self.id = id
        self.icon = icon
        self.title = title
        self.detail = detail
        self.tint = tint
    }
}

/// Breakdown of samples by their source device (e.g. Apple Watch vs iPhone).
struct SourceSlice: Identifiable, Hashable {
    var id: String { name }
    let name: String
    let count: Int
    let fraction: Double
}
